# Generated by Django 3.0.7 on 2020-06-27 17:40

from django.db import migrations

def create_data(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Student(name="Luis Ramon", email="luisramon1019@gmail.com", document="22342342", phone="0995900701").save()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
	migrations.RunPython(create_data),
    ]
